- name: instalar apache
  apt:
    name: apache2
    state: latest
    update_cache: yes
    
- name: si o si apache encendido
  service:
    name: apache2
    state: started
    enabled: yes

# systemctl start apache2

- name: que pase el cortafuegos
  raw: "ufw allow 'Apache'"
 