# Pod que lanza comandos de shell a través de args

apiVersion: v1
kind: Pod
metadata:
  name: dummy
  namespace: default
  labels:
    env: test
spec:
  containers:
  - name: dummy
    image: ubuntu
    # image: busybox
    args: [/bin/sh, -c, 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']

# Una vez creado el Pod podemos acceder a el haciendo
# kubectl exec -it dummy bash