version: "3.4"
services:
  dockerapp:
    build:
      context: .
    ports:
      - "8080:5000"
    depends_on:
      - redis
  dockerapp_imagen:
    image: isotomor/app_redis:v1.0
    ports:
      - "5005:5000"
    depends_on:
      - redis
  redis:
    image: redis:6.2.5-alpine3.14