trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'armEjemplo'
    ScriptType: 'FilePath'
    ScriptPath: './CreatePipelinePS/Deploy-AzTemplate.ps1'
    ScriptArguments: -Location 'westeurope' -ResourceGroupName 'josecitogrupoarm' -TemplateFile templates\mainTemplate.json
    azurePowerShellVersion: 'LatestVersion'