apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: sonda-liveness
spec:
  containers:
  - name: pod-liveness
    image: busybox:1.24
    command: ["/bin/sh","-c"]
    args: ["mkdir /tmp/prueba; sleep 10; rm -rf /tmp/prueba; sleep 10"]
    livenessProbe:
      exec:
        command:
        - ls
        - /tmp/prueba
      initialDelaySeconds: 5
      periodSeconds: 5

