# Ahora lo que hacemos es meter el mismo pod que hemos visto antes en un deployment, donde a parte de poder definir
# El por, podremos definir cuantas réplicas querremos de este pod. Si por ejemplo eliminamos un POD. o se cae por
# Algún motivo, al definir que tiene dos répilicas, se levantará una automáticamente.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-site
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web    
  template:
    metadata:
      name: pod-site
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: nginx
          ports:
            - containerPort: 80
        - name: rss-reader
          image: isotomor/rss
          ports:
            - containerPort: 88

# kubectl create -f deployment.yaml
# kubectl get deployments
# kubectl describe deployment rss-site