apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  volumes:
  - name: html
    emptyDir: {}
    
  containers:
  - name: sitio
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      
  initContainers:
  - name: descarga-git
    image: alpine/git:1.0.17
    command: ["/bin/sh","-c"]
    args: ["git clone https://github.com/nahuic72/website /html"]
    volumeMounts:
    - name: html
      mountPath: /html/
    