apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: datos-redis
      mountPath: /data/redis
      
  - name: busy
    image: busybox
    command: ["/bin/sh","-c"]
    args: ['echo "hola que tal">> /data/busy/fichero.log']

    volumeMounts:
    - name: datos-redis
      mountPath: /data/busy
      
  # lugar real en algun punto de algun nodo del cluster    
  volumes:
  - name: datos-redis
    emptyDir: {}