apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: curso
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1 
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers: 
      - name: mariadb
        image: curkub/cursokubernetesmariadb:latest
        ports:
        - containerPort: 3306
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: admin1234



