---
- name: Configurar SSH 
  hosts: all
  tasks:
     - name: Editar la configuracion SSH
       blockinfile:
         path: /etc/ssh/sshd_config
         block: |
            MaxAuthTries 4
            Banner /etc/motd
            X11Forwarding no
       notify: reinicia ssh

  handlers: 
    - name: reinicia ssh
      service:
        name: sshd
        state: restarted